import { StudentEntity } from '@/../mega-k-headhunter-back/src/types'
export const studentMock: StudentEntity[] = [
  {
    id: "1",
    email: "johndoe@example.com",
    phoneNumber: "555-555-5555",
    firstName: "John",
    lastName: "Doe",
    githubUsername: "johndoe",
    portfolioUrls: null,
    projectUrls: "https://github.com/johndoe/my-project",
    bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    expectedTypeWork: 1,
    targetWorkCity: "New York",
    expectedContractType: 2,
    expectedSalary: 60000,
    canTakeApprenticeship: false,
    monthsOfCommercialExp: 12,
    education: "Bachelor's degree",
    workExperience: "Software Engineer at XYZ Corp.",
    courses: "React, Node.js",
    isActive: true,
    status: 1,
  },
  {
    id: "2",
    email: "janedoe@example.com",
    phoneNumber: null,
    firstName: "Jane",
    lastName: "Doe",
    githubUsername: "janedoe",
    portfolioUrls: "https://janedoe.com/portfolio",
    projectUrls: "https://github.com/janedoe/my-project",
    bio: null,
    expectedTypeWork: 2,
    targetWorkCity: "San Francisco",
    expectedContractType: 1,
    expectedSalary: 80000,
    canTakeApprenticeship: true,
    monthsOfCommercialExp: 24,
    education: "Master's degree",
    workExperience: "Software Engineer at ABC Corp.",
    courses: null,
    isActive: true,
    status: 1,
  },
  {
    id: "3",
    email: "bobsmith@example.com",
    phoneNumber: "555-555-1234",
    firstName: "Bob",
    lastName: "Smith",
    githubUsername: "bobsmith",
    portfolioUrls: "https://bobsmith.com/portfolio",
    projectUrls: "https://github.com/bobsmith/my-project",
    bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed faucibus dui vel pretium mollis.",
    expectedTypeWork: 3,
    targetWorkCity: null,
    expectedContractType: 2,
    expectedSalary: null,
    canTakeApprenticeship: false,
    monthsOfCommercialExp: 6,
    education: "High School Diploma",
    workExperience: null,
    courses: "Python",
    isActive: false,
    status: 2,
  },
];