import { StudentEntity } from '@/types'


export const studentMock: StudentEntity[]  = [
  {
    id: "1",
    email: "johndoe@example.com",
    phoneNumber: "555-555-5555",
    firstName: "John",
    lastName: "Doe",
    githubUsername: "johndoe",
    portfolioUrls: null,
    projectUrls: "https://github.com/johndoe/my-project",
    bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    expectedTypeWork: 1,
    targetWorkCity: "New York",
    expectedContractType: 2,
    expectedSalary: 60000,
    canTakeApprenticeship: false,
    monthsOfCommercialExp: 12,
    education: "Bachelor's degree",
    workExperience: "Software Engineer at XYZ Corp.",
    courses: "React, Node.js",
    isActive: true,
    status: 1,
    grades: {
      courseCompletion: 2,
      courseEngagement: 3,
      projectDegree: 4,
      teamProjectDegree: 5,
    },
  },
  {
    id: "2",
    email: "janedoe@example.com",
    phoneNumber: null,
    firstName: "Jane",
    lastName: "Doe",
    githubUsername: "janedoe",
    portfolioUrls: "https://janedoe.com/portfolio",
    projectUrls: "https://github.com/janedoe/my-project",
    bio: null,
    expectedTypeWork: 2,
    targetWorkCity: "San Francisco",
    expectedContractType: 1,
    expectedSalary: 80000,
    canTakeApprenticeship: true,
    monthsOfCommercialExp: 24,
    education: "Master's degree",
    workExperience: "Software Engineer at ABC Corp.",
    courses: null,
    isActive: true,
    status: 1,
    grades: {
      courseCompletion: 3,
      courseEngagement: 2,
      projectDegree: 5,
      teamProjectDegree: 4,
    },
  },
  {
    id: "3",
    email: "bobsmith@example.com",
    phoneNumber: "555-555-1234",
    firstName: "Bob",
    lastName: "Smith",
    githubUsername: "bobsmith",
    portfolioUrls: "https://bobsmith.com/portfolio",
    projectUrls: "https://github.com/bobsmith/my-project",
    bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed faucibus dui vel pretium mollis.",
    expectedTypeWork: 3,
    targetWorkCity: null,
    expectedContractType: 2,
    expectedSalary: null,
    canTakeApprenticeship: false,
    monthsOfCommercialExp: 6,
    education: "High School Diploma",
    workExperience: null,
    courses: "Python",
    isActive: false,
    status: 2,
    grades: {
      courseCompletion: 1,
      courseEngagement: 4,
      projectDegree: 2,
      teamProjectDegree: 3,
    },
  },
  {
    id: "4",
    email: "janedoe@example.com",
    phoneNumber: null,
    firstName: "Jane",
    lastName: "Doe",
    githubUsername: "janedoe",
    portfolioUrls: null,
    projectUrls: "https://github.com/janedoe/my-project",
    bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec luctus vel lacus vitae pharetra.",
    expectedTypeWork: 1,
    targetWorkCity: "London",
    expectedContractType: 1,
    expectedSalary: 50000,
    canTakeApprenticeship: true,
    monthsOfCommercialExp: 12,
    education: "Bachelor's Degree in Computer Science",
    workExperience: "Software Developer at XYZ Company",
    courses: "Java, JavaScript, React",
    isActive: true,
    status: 1,
    grades: {
      courseCompletion: 5,
      courseEngagement: 3,
      projectDegree: 4,
      teamProjectDegree: 4,
    },
  },
  {
    id: "5",
    email: "johnsmith@example.com",
    phoneNumber: "555-555-5678",
    firstName: "John",
    lastName: "Smith",
    githubUsername: "johnsmith",
    portfolioUrls: "https://johnsmith.com/portfolio",
    projectUrls: 'null',
    bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce aliquam purus sed nibh scelerisque hendrerit.",
    expectedTypeWork: 2,
    targetWorkCity: "New York",
    expectedContractType: 2,
    expectedSalary: 70000,
    canTakeApprenticeship: false,
    monthsOfCommercialExp: 24,
    education: "Master's Degree in Computer Engineering",
    workExperience: "Frontend Developer at ABC Company",
    courses: "React Native, Redux, Node.js",
    isActive: true,
    status: 1,
    grades: {
      courseCompletion: 4,
      courseEngagement: 4,
      projectDegree: 5,
      teamProjectDegree: 3,
    },
  },
  {
    id: "6",
    email: "janesmith@example.com",
    phoneNumber: null,
    firstName: "Jane",
    lastName: "Smith",
    githubUsername: "janesmith",
    portfolioUrls: null,
    projectUrls: "https://github.com/janesmith/my-project",
    bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean vel magna id nisi consequat bibendum.",
    expectedTypeWork: 3,
    targetWorkCity: "San Francisco",
    expectedContractType: 1,
    expectedSalary: 80000,
    canTakeApprenticeship: true,
    monthsOfCommercialExp: 36,
    education: "PhD in Computer Science",
    workExperience: "Senior Software Engineer at XYZ Company",
    courses: "Python, Machine Learning, Data Science",
    isActive: false,
    status: 2,
    grades: {
      courseCompletion: 3,
      courseEngagement: 5,
      projectDegree: 3,
      teamProjectDegree: 4,
    },
  }
];